const productos = [
    {
        url: "https://i.imgur.com/XmcNCPD.jpeg",
        nombre: "Eco Start 7",
        descripcion: "Calefactor a pellet Eco Start 7 7kW ",
        caracteristicas: {"Potencia (kw)": "7 Kw", "Capacidad de la tolva": "6 kg", "Autonomía": "5 / 10 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "1",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: true
    },
    {
        url: "https://i.imgur.com/LX47tjy.jpeg",
        nombre: "Petit",
        descripcion: "Calefactor a pellet Petit 5kg",
        caracteristicas: {"Potencia (kw)": "5 Kw", "Capacidad de la tolva": "3 kg", "Autonomía": "4 / 6 hs"},
        otros: ["Control remoto.", "Incluye kit para conexión por wifi y kit de instalación."],
        precio: 0,
        moneda: "USD",
        idx: "2",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: true
    },
    {
        url: "https://i.imgur.com/3E92Yix.jpeg",
        nombre: "Eco Start 10",
        descripcion: "Calefactor a pellet Eco Start 10 10kW ",
        caracteristicas: {"Potencia (kw)": "10 Kw", "Capacidad de la tolva": "8 kg", "Autonomía": "6 / 13 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "3",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: false
    },
    {
        url: "https://i.imgur.com/aob6y6d.jpeg",
        nombre: "Eco Start 12",
        descripcion: "Calefactor a pellet Eco Start 12 12kW",
        caracteristicas: {"Potencia (kw)": "12 Kw", "Capacidad de la tolva": "10 kg", "Autonomía": "6 / 18 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "4",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: false
    },
    {
        url: "https://i.imgur.com/Mxr3oJJ.jpeg",
        nombre: "Piccola",
        descripcion: "Calefactor a pellet Piccola 6kW",
        caracteristicas: {"Potencia (kw)": "6 Kw", "Capacidad de la tolva": "8 kg", "Autonomía": "6 / 12 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "5",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: false
    },
    {
        url: "https://i.imgur.com/KRH1ekD.jpeg",
        nombre: "Bambina",
        descripcion: "Calefactor a pellet Bambina 6kW",
        caracteristicas: {"Potencia (kw)": "6 Kw", "Capacidad de la tolva": "6 kg", "Autonomía": "5 / 10 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "6",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: false
    },
    {
        url: "https://i.imgur.com/QQmPfpk.jpeg",
        nombre: "Donna",
        descripcion: "Calefactor a pellet Donna 9kW",
        caracteristicas: {"Potencia (kw)": "9 Kw", "Capacidad de la tolva": "9 kg", "Autonomía": "5 / 11 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "7",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: false
    },
    {
        url: "https://i.imgur.com/TPU80fU.jpeg",
        nombre: "Donna Plus",
        descripcion: "Calefactor a pellet Donna Plus 12kW",
        caracteristicas: {"Potencia (kw)": "12 Kw", "Capacidad de la tolva": "20 kg", "Autonomía": "8 / 25 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "8",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: false
    },
    {
        url: "https://i.imgur.com/pkYaUAq.jpeg",
        nombre: "Lupe",
        descripcion: "Calefactor a pellet Lupe 8 / 8,5kW",
        caracteristicas: {"Potencia (kw)": "8 / 8,5 Kw", "Capacidad de la tolva": "13 kg", "Autonomía": "7,2 / 11,5 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "9",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: false
    },
    {
        url: "https://i.imgur.com/iZlMTMA.jpeg",
        nombre: "Nina",
        descripcion: "Calefactor a pellet Nina 8kW",
        caracteristicas: {"Potencia (kw)": "8 Kw", "Capacidad de la tolva": "16 kg", "Autonomía": "8,5 / 18 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "10",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: false
    },
    {
        url: "https://i.imgur.com/WTyEZsk.jpeg",
        nombre: "Esquinera Vivion",
        descripcion: "Calefactor a pellet Esquinera Vivion 9kW",
        caracteristicas: {"Potencia (kw)": "9 Kw", "Capacidad de la tolva": "8 kg", "Autonomía": "4 / 10 hs"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "11",
        categoria: "calefactores",
        subcategoria: "pellet",
        destacado: true
    },
    {
        url: "https://i.imgur.com/owBLPxL.jpeg",
        nombre: "ECOMINI 7,5KW",
        descripcion: "Estufa de alto rendimiento EcoMini 7,5kW",
        caracteristicas: {"Consumo": "2,1 kg/hr", "Vol. calefactable (m2/m3)": "72 / 180", "Combustible largo máximo (cm)": "53 cm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "101",
        categoria: "calefactores",
        subcategoria: "leña",
        destacado: true
    },
    {
        url: "https://i.imgur.com/yPJVOpc.jpeg",
        nombre: "ECOMÁXIMA 8,5KW",
        descripcion: "Estufa alto rendimiento a leña EcoMáxima 8,5 kW",
        caracteristicas: {"Consumo": "4,1 kg/hr", "Vol. calefactable (m2/m3)": "80 / 200", "Combustible largo máximo (cm)": "50 cm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "102",
        categoria: "calefactores",
        subcategoria: "leña",
        destacado: true
    },
    {
        url: "https://i.imgur.com/NjK9fnI.jpeg",
        nombre: "ECOMÁXIMA 9,5KW",
        descripcion: "Estufa alto rendimiento a leña EcoMáxima 9,5 kW",
        caracteristicas: {"Consumo": "4,1 kg/hr", "Vol. calefactable (m2/m3)": "92 / 230", "Combustible largo máximo (cm)": "50 cm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "103",
        categoria: "calefactores",
        subcategoria: "leña",
        destacado: true
    },
    {
        url: "https://i.imgur.com/bUMpo08.jpeg",
        nombre: "ECOMÁXIMA 11KW",
        descripcion: "Estufa de alto rendimiento EcoMáxima 11 kW",
        caracteristicas: {"Consumo": "5,1 kg/hr", "Vol. calefactable (m2/m3)": "108 / 270", "Combustible largo máximo (cm)": "40 cm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "104",
        categoria: "calefactores",
        subcategoria: "leña",
        destacado: false
    },
    {
        url: "https://i.imgur.com/wm4ahrl.jpeg",
        nombre: "ECOMÁXIMA 13,5KW",
        descripcion: "Estufa de alto rendimiento EcoMáxima 13,5kW",
        caracteristicas: {"Consumo": "3,8 kg/hr", "Vol. calefactable (m2/m3)": "132 / 330", "Combustible largo máximo (cm)": "60 cm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "105",
        categoria: "calefactores",
        subcategoria: "leña",
        destacado: false
    },
    {
        url: "https://i.imgur.com/sTxLOfr.jpeg",
        nombre: "Lerma",
        descripcion: "Estufa alto rendimiento a leña Lerma 8,7kW",
        caracteristicas: {"Consumo": "2,2 kg/hr", "Vol. calefactable (m2/m3)": "90 / 225", "Combustible largo máximo (cm)": "43 cm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "106",
        categoria: "calefactores",
        subcategoria: "leña",
        destacado: true
    },
    {
        url: "https://i.imgur.com/S89llBU.jpeg",
        nombre: "AA SMART Stratos INVERTER",
        descripcion: "AA Smart Stratos Inverter 9.000 BTU UVC",
        caracteristicas: {"Capacidad de enfriamiento": "9.000 BTU/h", "Medidas Unidad Interior": "720 x 196 x 270 mm (l x a x h)", "Medidas Unidad Exterior": "660 x 250 x 530 mm (l x a x h)"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "201",
        categoria: "aires acondicionados",
        destacado: true
    },
    {
        url: "https://i.imgur.com/IQYZStx.jpeg",
        nombre: "AA SMART Stratos INVERTER",
        descripcion: "AA Smart Stratos Inverter 12.000 BTU UVC",
        caracteristicas: {"Capacidad de enfriamiento": "12.000 BTU/h", "Medidas Unidad Interior": "82 x 27 x 19 cm (l x a x h)", "Medidas Unidad Exterior": "78 x 27 x 56 cm (l x a x h)"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "202",
        categoria: "aires acondicionados",
        destacado: false
    },
    {
        url: "https://i.imgur.com/IQYZStx.jpeg",
        nombre: "AA SMART Stratos INVERTER",
        descripcion: "AA Smart Stratos Inverter 18.000 BTU UVC",
        caracteristicas: {"Capacidad de enfriamiento": "18.000 BTU/h", "Medidas Unidad Interior": "105 x 27 x 22 cm (l x a x h)", "Medidas Unidad Exterior": "78 x 27 x 56 cm (l x a x h)"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "203",
        categoria: "aires acondicionados",
        destacado: false
    },
    {
        url: "https://i.imgur.com/IQYZStx.jpeg",
        nombre: "AA SMART Stratos INVERTER",
        descripcion: "AA Smart Stratos Inverter 24.000 BTU UVC",
        caracteristicas: {"Capacidad de enfriamiento": "24.000 BTU/h", "Medidas Unidad Interior": "105 x 32 x 22 cm (l x a x h)", "Medidas Unidad Exterior": "87 x 31,7 x 71 cm (l x a x h)"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "204",
        categoria: "aires acondicionados",
        destacado: true
    },
    {
        url: "https://i.imgur.com/kxvZhMq.jpeg",
        nombre: "AA SMART VIVION ON-OFF",
        descripcion: "AA Smart Vivion On-Off 9.000 BTU",
        caracteristicas: {"Capacidad de enfriamiento": "9.000 BTU/h", "Medidas Unidad Interior": "720 x 270 x 200 mm", "Medidas Unidad Exterior": "660 x 421 x 250 mm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "205",
        categoria: "aires acondicionados",
        destacado: true
    },
    {
        url: "https://i.imgur.com/kxvZhMq.jpeg",
        nombre: "AA SMART VIVION ON-OFF",
        descripcion: "AA Smart Vivion On-Off 12.000 BTU",
        caracteristicas: {"Capacidad de enfriamiento": "12.000 BTU/h", "Medidas Unidad Interior": "720 x 270 x 200 mm", "Medidas Unidad Exterior": "660 x 530 x 250 mm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "206",
        categoria: "aires acondicionados",
        destacado: false
    },
    {
        url: "https://i.imgur.com/kxvZhMq.jpeg",
        nombre: "AA SMART VIVION ON-OFF",
        descripcion: "AA Smart Vivion On-Off 18.000 BTU",
        caracteristicas: {"Capacidad de enfriamiento": "18.000 BTU/h", "Medidas Unidad Interior": "900 x 291 x 215 mm", "Medidas Unidad Exterior": "780 x 560 x 270 mm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "207",
        categoria: "aires acondicionados",
        destacado: false
    },
    {
        url: "https://i.imgur.com/kxvZhMq.jpeg",
        nombre: "AA SMART VIVION ON-OFF",
        descripcion: "AA Smart Vivion On-Off 24.000 BTU",
        caracteristicas: {"Capacidad de enfriamiento": "24.000 BTU/h", "Medidas Unidad Interior": "900 x 291 x 215 mm", "Medidas Unidad Exterior": "819 x 638 x 309 mm"},
        otros: [],
        precio: 0,
        moneda: "USD",
        idx: "208",
        categoria: "aires acondicionados",
        destacado: false
    }
]

export default productos;